INSERT INTO `tmp` (`key`, `value`, `desc`) VALUES ('System.Start', NOW(), 'System start time.');
INSERT INTO `h_user` (`id`,`email`, `name`, `password`) VALUES ('9999999999', 'a0911558945@gmail.com', '莊承翰(管理者)','123');
INSERT INTO `INTERESTS` (`INTERESTS_CODE`,`INTERESTS_VALUE`) VALUES ('Movie', '電影');
INSERT INTO `INTERESTS` (`INTERESTS_CODE`,`INTERESTS_VALUE`) VALUES ('Food', '美食');
INSERT INTO `INTERESTS` (`INTERESTS_CODE`,`INTERESTS_VALUE`) VALUES ('Sport', '運動');
INSERT INTO `INTERESTS` (`INTERESTS_CODE`,`INTERESTS_VALUE`) VALUES ('Travel', '旅遊');
INSERT INTO `INTERESTS` (`INTERESTS_CODE`,`INTERESTS_VALUE`) VALUES ('Music', '音樂');
INSERT INTO `USER_INTERESTS` (`ID`,`USER_ID`,`INTERESTS_CODE`) VALUES ('123123','9999999999', 'Music');