set mode MySQL;

DROP TABLE IF EXISTS tmp;
CREATE TABLE tmp (
    key VARCHAR(50) NOT NULL, 
    value VARCHAR(200) DEFAULT NULL, 
    desc VARCHAR(200) DEFAULT NULL, 
    PRIMARY KEY (key)
);

//會員主檔
DROP TABLE IF EXISTS H_USER ;
CREATE TABLE H_USER (
    ID VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL, 
    NAME VARCHAR(200) NOT NULL, 
    PASSWORD VARCHAR(50) NOT NULL, 
    PICTURE_ID VARCHAR(50),
    PRIMARY KEY (ID)
);

//會員修改紀錄
DROP TABLE IF EXISTS USER_RECORD ;
CREATE TABLE USER_RECORD (
    USER_ID VARCHAR(50) NOT NULL, 
    CHANGETIME VARCHAR(200), 
    CHANGEDETAIL VARCHAR(200)  
);

-- 圖檔table
DROP TABLE IF EXISTS REF_IMAGE ;
CREATE TABLE REF_IMAGE (
    ID VARCHAR(50) NOT NULL, 
    USER_ID VARCHAR(200) NOT NULL, 
    ATTACH_NAME VARCHAR(200) NOT NULL, 
    IMG_URL VARCHAR(200) NOT NULL, 
    IMG_SIZE VARCHAR(200) NOT NULL, 
    PRIMARY KEY (ID)
);

-- 使用者興趣
DROP TABLE IF EXISTS USER_INTERESTS ;
CREATE TABLE USER_INTERESTS (
    ID VARCHAR(50) NOT NULL, 
    USER_ID VARCHAR(200) NOT NULL, 
    INTERESTS_CODE VARCHAR(50) NOT NULL, 
    PRIMARY KEY (ID)
);

-- 興趣對應中文
DROP TABLE IF EXISTS INTERESTS ;
CREATE TABLE INTERESTS (
    INTERESTS_CODE VARCHAR(50) NOT NULL, 
    INTERESTS_VALUE VARCHAR(200) NOT NULL, 
    PRIMARY KEY (INTERESTS_CODE)
);

-- API功能
DROP TABLE IF EXISTS API_FUNCTION ;
CREATE TABLE API_FUNCTION (
	API_CODE VARCHAR(50) NOT NULL, 
    API_NAME VARCHAR(50) NOT NULL, 
    API_URL VARCHAR(50) NOT NULL, 
	API_CLASS VARCHAR(50) NOT NULL,
	USE_OPEN VARCHAR(50) NOT NULL,
    API_DEPT VARCHAR(100),
    PRIMARY KEY (API_CODE)
);

-- API數據統計
DROP TABLE IF EXISTS API_COURSE ;
CREATE TABLE API_COURSE (
    ID VARCHAR(50) NOT NULL, 
    API_URL VARCHAR(50) NOT NULL, 
    API_CODE VARCHAR(50) NOT NULL, 
	CALL_USER VARCHAR(50) NOT NULL,
	CALL_TIME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

