set mode MySQL;

DROP TABLE IF EXISTS tmp;
CREATE TABLE tmp (
    key VARCHAR(50) NOT NULL, 
    value VARCHAR(200) DEFAULT NULL, 
    desc VARCHAR(200) DEFAULT NULL, 
    PRIMARY KEY (key)
);

DROP TABLE IF EXISTS H_USER ;
CREATE TABLE H_USER (
    ID VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(200) NOT NULL, 
    NAME VARCHAR(200) NOT NULL, 
    PASSWORD VARCHAR(200) NOT NULL, 
    PICTURE_ID VARCHAR(300),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS USER_RECORD ;
CREATE TABLE USER_RECORD (
    USER_ID VARCHAR(50) NOT NULL, 
    CHANGETIME VARCHAR(200), 
    CHANGEDETAIL VARCHAR(200)  
);

DROP TABLE IF EXISTS REF_IMAGE ;
CREATE TABLE REF_IMAGE (
    ID VARCHAR(50) NOT NULL, 
    USER_ID VARCHAR(200) NOT NULL, 
    ATTACH_NAME VARCHAR(200) NOT NULL, 
    IMG_URL VARCHAR(200) NOT NULL, 
    PRIMARY KEY (ID)
);

